package model

// User model old structure from PDS-API
type User struct {
	UserAiid                  string `json:"user_AIID"`
	JenisIdentitas            string `json:"jenis_identitas"`
	NoKtp                     string `json:"no_ktp"`
	TanggalExpiredIdentitas   string `json:"tanggal_expired_identitas"`
	Cif                       string `json:"cif"`
	Email                     string `json:"email"`
	NoHp                      string `json:"no_hp"`
	Password                  string `json:"password"`
	NextPasswordReset         string `json:"next_password_reset"`
	Pin                       string `json:"pin"`
	Nama                      string `json:"nama"`
	NamaIbu                   string `json:"nama_ibu"`
	JenisKelamin              string `json:"jenis_kelamin"`
	TempatLahir               string `json:"tempat_lahir"`
	Agama                     string `json:"agama"`
	TglLahir                  string `json:"tgl_lahir"`
	Alamat                    string `json:"alamat"`
	Domisili                  string `json:"domisili"`
	Kewarganegaraan           string `json:"kewarganegaraan"`
	StatusKawin               string `json:"status_kawin"`
	Kodepos                   string `json:"kodepos"`
	IdKelurahan               string `json:"id_kelurahan"`
	NoNpwp                    string `json:"no_npwp"`
	FotoNpwp                  string `json:"foto_npwp"`
	NoSid                     string `json:"no_sid"`
	FotoSid                   string `json:"foto_sid"`
	KodeCabang                string `json:"kode_cabang"`
	FotoUrl                   string `json:"foto_url"`
	FotoKtpUrl                string `json:"foto_ktp_url"`
	Status                    int64  `json:"status"`
	IsLocked                  string `json:"is_locked"`
	LoginFailCount            int64  `json:"login_fail_count"`
	EmailVerified             int64  `json:"email_verified"`
	KycVerified               int64  `json:"kyc_verified"`
	EmailVerificationToken    string `json:"email_verification_token"`
	Token                     string `json:"token"`
	TokenWeb                  string `json:"token_web"`
	FcmToken                  string `json:"fcm_token"`
	LastUpdate                string `json:"last_update"`
	Norek                     string `json:"norek"`
	Saldo                     int64  `json:"saldo"`
	PinTemp                   string `json:"pin_temp"`
	LastUpdateDataNasabah     string `json:"last_update_data_nasabah"`
	LastUpdateDataNpwp        string `json:"last_update_data_npwp"`
	LastUpdateLinkCif         string `json:"last_update_link_cif"`
	LastUpdateUnlinkCif       string `json:"last_update_unlink_cif"`
	LastUpdatePin             string `json:"last_update_pin"`
	AktifasiTransFinansial    string `json:"aktifasiTransFinansial"`
	TanggalAktifasiFinansial  string `json:"tanggal_aktifasi_finansial"`
	IsDukcapilVerified        int64  `json:"is_dukcapil_verified"`
	IsOpenTe                  int64  `json:"is_open_te"`
	ReferralCode              string `json:"referral_code"`
	GoldcardApplicationNumber string `json:"goldcard_application_number"`
	GoldcardAccountNumber     string `json:"goldcard_account_number"`
	TryLoginDate              string `json:"try_login_date"`
	WrongPasswordCount        int64  `json:"wrong_password_count"`
	BlockedDate               string `json:"blocked_date"`
	BlockedToDate             string `json:"blocked_to_date"`
	NorekUtama                string `json:"norek_utama"`
	IsSetBiometric            int64  `json:"is_set_biometric"`
	DeviceIdBiometric         string `json:"device_id_biometric"`
}
